var isArea = require('../')
var test = require('tape')

test('is-area', function (t) {
  t.ok(isArea({ 'natural' : 'wood' }))
  t.notOk(isArea({ 'highway': 'primary', 'surface': 'asphalt' }))
  t.notOk(isArea({ 'highway': 'service' }))
  t.ok(isArea({ 'waterway': 'riverbank' }))
  t.ok(isArea({ 'name': 'Щербачевский лес', 'natural': 'wood' }))
  t.ok(isArea({ 'name': 'Лісовий заказник «Григорівський бір»', 'boundary': 'protected_area' }))
  t.ok(isArea({ 'area': 'yes', 'name': '6 платформа', 'railway': 'platform' }))
  t.ok(isArea({ 'name': 'Зустріч', 'leisure': 'park', 'name:ru': 'Парк «Зустрич»' }))
  t.ok(isArea({ 'fee': 'no', 'amenity': 'parking', 'parking': 'surface' }))
  t.notOk(isArea({ 'highway': 'tertiary' }))
  t.ok(isArea({ 'landuse': 'landfill' }))
  t.notOk(isArea({ 'name': 'Роганка', 'name:en': 'Rohanka', 'name:ru': 'Роганка', 'waterway': 'river' }))
  t.notOk(isArea({ 'highway': 'primary_link', 'surface': 'asphalt' }))
  t.ok(isArea( { 'name': 'Харківський Політехнічний Інститут', 'amenity': 'university', 'name:de': 'Polytechnisches Institut Charkiw', 'name:en': 'Kharkiv Polytechnic Institute', 'name:uk': 'Харківський Політехнічний Інститут', 'name:zh': '哈尔科夫理工学院', 'website': 'http://www.kpi.kharkov.ua', 'wikidata': 'Q1164068' }))
  t.ok(isArea({ 'name': 'Завод ім. Малишева', 'landuse': 'industrial', 'name:ru': 'Завод им. Малышева'})) 
  t.notOk(isArea({ 'name': 'Новаторський в’їзд', 'highway': 'service', 'name:ru': 'Новаторский въезд', 'name:uk': 'Новаторський в’їзд' }))
  t.notOk(isArea({ 'highway': 'unclassified' }))
  t.notOk(isArea({}))
  t.ok(isArea({ 'building': 'yes' }))
  t.ok(isArea({ 'landuse': 'grass' }))
  t.ok(isArea({ 'name': 'Спорткомплекс "Планета"', 'leisure': 'sports_centre', 'building': 'yes' }))
  t.notOk(isArea({ 'layer': '-5', 'tunnel': 'yes', 'railway': 'subway' }))
  t.notOk(isArea({ 'gauge': '1520', 'usage': 'main', 'railway': 'rail', 'voltage': '3000', 'frequency': '0', 'electrified': 'contact_line' }))
  t.notOk(isArea( { 'boat': 'no', 'name': 'Харків', 'name:en': 'Kharkiv', 'name:ru': 'Харьков', 'waterway': 'river' }))
  t.ok(isArea({ 'boat': 'no', 'name': 'Харків', 'name:en': 'Kharkiv', 'name:ru': 'Харьков', 'waterway': 'riverbank' }))
  t.notOk(isArea({ 'barrier': 'fence' }))
  t.ok(isArea({ 'natural': 'water' }))
  t.ok(isArea({ 'water': 'reservoir', 'natural': 'water' }))
  t.ok(isArea({ 'amenity': 'place_of_worship', 'building': 'yes', 'religion': 'muslim' }))
  t.ok(isArea({ 'name': 'Велта', 'shop': 'mall', 'building': 'yes', 'addr:city': 'Харьков' }))
  t.notOk(isArea({ 'waterway': 'stream' }))
  t.ok(isArea({ 'sport': 'soccer', 'leisure': 'pitch' }))
  t.ok(isArea({ 'area': 'yes', 'railway': 'turntable' }))
  // { railway: 'subway', service: 'yard' } service isn't in the list
  t.notOk(isArea({ 'railway': 'tram' }))
  t.ok(isArea({ 'building': 'yes', 'abandoned': 'yes' }))

  t.end()
})
